### ISSUE TITLE
corrupted file visio 2010 plugin

### ISSUE THREAD

**Issue by cachemoney** [nbelyh/svgpublish-templates#1]
![visioerror](https://user-images.githubusercontent.com/477635/35990010-9913bfea-0cb7-11e8-9a61-c5b74a9e17eb.png)

Hi, Im on windows 7, Ive uninstalled the plugin and reinstalled the plugin and this error still pops up.  Any suggestions?  Thanks!

**Comment by nbelyh** [comment]
Hi, could you please try to just drop this configuration file mentioned in that dialog, it's okay, just the settings will be reset (but before deleting, could you please send it to me for checking what's wrong).

**Comment by nbelyh** [comment]
The application was unable to load settings from the previous version from the user configuration. Now it should start nevertheless, and just reset settings if something goes wrong here
