### ISSUE TITLE
Support/verify modern (2f) authentication

### ISSUE THREAD

**Issue by nbelyh** [nbelyh/svgpublish-templates#20]
Verify that extension works with 2F authentication and SharePoint online

Check value of the flag "LegacyAuthProtocolsEnabled" on your SharePoint site (if legacy authentication protocols are disabled for your site):

Connect-SPOService -Url https://xxxxxx.sharepoint.com
Get-SPOTenant | Select LegacyAuthProtocolsEnabled

Looks like in case legacy protocols are disabled, there is this exception: Cannot contact web site 'XXXX-admin.sharepoint.com' or the web site does not support SharePoint Online credentials

**Comment by nbelyh** [comment]
Moern Authentication is implemented in PnP Core for example.

**Comment by nbelyh** [comment]
Fixed with https://github.com/nbelyh/svgpublish/pull/10

**Comment by nbelyh** [comment]
Ensure that the login dialog is raised anyways. Now also in case when legacy authentication is turned off.

![image](https://user-images.githubusercontent.com/528366/74592880-f1440400-5025-11ea-8f0e-3fb773b41f0d.png)

**Comment by BDein** [comment]
This close issue seems to be fixed by 215 - thanks
