### ISSUE TITLE
SharePoint page is saved as "draft"

### ISSUE THREAD

**Issue by nbelyh** [nbelyh/svgpublish-templates#24]
If you export a diagram to SharePoint, by default it is saved in "Draft" state. This makes it invisible to "Visitors" of the site. To open it to "Visitors" you have to "publish" it again with menu:

![image](https://user-images.githubusercontent.com/528366/76372780-c86e1080-633e-11ea-9426-652f80b64561.png)

The extension should publish the diagram by default (or at least provide a checkbox to do that automatically)

**Comment by BDein** [comment]
I partly have the same issue, but it's when exporting multiple Visio pages, then it complains: 
![image](https://user-images.githubusercontent.com/25555274/77426381-a790cb00-6dd4-11ea-9344-08492be2add3.png), and I also pretty much know why, as I just changed our SharePoint to not only save Major but both Major and Minor versions.
I think this needs a fix:-)

**Comment by BDein** [comment]
Hi Nikolay,
How is the progress on this issue?

**Comment by nbelyh** [comment]
@BDein Not yet... Will update this issue as soon as there are news. I'd in a few weeks probably.

**Comment by nbelyh** [comment]
Should be fixed in release 1.3 https://github.com/nbelyh/svgpublish/pull/13
Now the export creates a major version if minor/major versioning is enabled, and publishes it.
