### ISSUE TITLE
Tooltips and Popovers are not working

### ISSUE THREAD

**Issue by BDein** [nbelyh/svgpublish-templates#27]
In release 1.2.12.215 the tooltips and popovers hover over and click is not poping up as they use to in the previous version, but the shapes only get marked as shown here:
![image](https://user-images.githubusercontent.com/25555274/77427628-00616300-6dd7-11ea-9385-dd77b9eaef44.png)

**Comment by nbelyh** [comment]
Dear @BDein did you re-publish after updating the version using the "Deploy" option? 
It should update the scripts

![image](https://user-images.githubusercontent.com/528366/77427936-939a9880-6dd7-11ea-9a2b-b7c9f391a7c7.png)

Could you please check the console log (F12)?

**Comment by BDein** [comment]
Yes - I did actually do this, but as we discussed today, there was this missing point of having a "description", properties an/or tooltip defined in the shapes to make it work.

So case solved - thanks 👍
