### ISSUE TITLE
I can't write markdown... (the editor is weird)

### ISSUE THREAD

**Issue by MickeyDragon** [nbelyh/svgpublish-templates#63]
I can't write markdown... (the editor is weird)
I can't type anything in the markdown editor.
It works fine in version 1.2
All versions above 1.3 are not supported...

I also enabled activeX, but it doesn't work...
![스크린샷_2021-06-25_17-11-28](https://user-images.githubusercontent.com/11529520/123392814-6b9c7500-d5d8-11eb-8678-92269ad1a84d.png)

**Comment by nbelyh** [comment]
Thank you for reporting!

The editor was reworked (I thought, improved 😄) in 1.3
Could you kindly provide some environment details, like Visio and OS version (maybe the log - you can enable it in the "About..." box?

**Comment by MickeyDragon** [comment]
Visio version tested: 2013,2016,2019 (64bit) Windows 10 I will record the problem with a video tomorrow... Sorry for not being able to explain in detail.

**Comment by nbelyh** [comment]
Now 1.4 supports the Edge runtime for rendering things (including editor)
Enabling this could help if the editor looks "dead":


![Image](https://user-images.githubusercontent.com/528366/197355655-b40c289a-6784-4769-a14c-5dee84c12eb9.png)
